### ISSUE TITLE
2x Uncaught DOMException Error (Node.appendChild, Node.removeChild)

### ISSUE THREAD

**Issue by tobiasriemenschneider** [netlify/remix-edge-template#22] opened 2022-05-17 05:00 UTC
Navigating to https://remix-edge-on.netlify.app/ leads to a white screen with uncaught errors in the console.
<img width="1240" alt="Bildschirmfoto 2022-05-17 um 06 57 11" src="https://user-images.githubusercontent.com/3159548/168732647-4cdba70c-fb83-4282-a1a3-7ec860f8b88f.png">

**Comment by Aprillion** [comment] 2022-05-18 09:19
Related to https://github.com/remix-run/remix/issues/2947 and https://github.com/facebook/react/issues/24430

**Comment by tobiasriemenschneider** [comment] 2022-05-26 05:06
Thanks @Aprillion for the references.
Any idea how I can get it to work until the final fixes have been shipped to React and the Remix-Edge-Template?

**Comment by Aprillion** [comment] 2022-05-26 20:48
no idea.. there was https://twitter.com/ryanflorence/status/1526278116527640576 that might have some suggestions to try, but I don't remember any satisfying solution from any place I've seen so far (but I don't actively seek solutions, I reverted to React 17 for the time being in my own remix project)

**Comment by tobiasriemenschneider** [comment] 2022-05-27 04:58
Thanks @Aprillion!
Than it might make sense to stick to React 17 with regards to this Remix-Edge-Template until it is solved, I would say.
For Production I consider this a showstopper, @nickytonline.

**Comment by nickytonline** [comment] 2023-02-10 03:55
I'm going to go ahead and close this because the issue is in React code. Follow along in this issue, https://github.com/facebook/react/issues/24430

As well the official template will be coming soon. It's based off of work in https://github.com/netlify/remix-compute/pull/16 and https://github.com/netlify/remix-edge-template/pull/83

**Closed by nickytonline** 2023-02-10 03:55 UTC
